In [1]:
import numpy as np

In [21]:
dosya_yollari = [
    "/content/d1.txt",
    "/content/d2.txt",
    "/content/d3.txt"
]

token_2_index = {}
token_index = 0
docs = []

for dosya_yolu in dosya_yollari:
    with open(dosya_yolu, "r") as f:
        icerik = f.readline()
        tokens = icerik.split(" ")
        docs.append(tokens)
        for token in tokens:
            if token not in token_2_index:
                token_2_index[token] = token_index
                token_index += 1

print(token_2_index)
print(docs)

{'a': 0, 'b': 1, 'c': 2, 'd': 3}
[['a', 'b', 'a', 'a', 'b'], ['a', 'b', 'c', 'a', 'b', 'c', 'c', 'd'], ['a', 'b', 'a', 'a', 'b', 'a', 'b', 'a', 'a', 'b']]


In [24]:
sayma_vektorleri = np.zeros((len(dosya_yollari), len(token_2_index)))

In [25]:
sayma_vektorleri

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
for i, doc in enumerate(docs):
    for token in doc:
        sayma_vektorleri[i][token_2_index[token]] += 1

In [30]:
sayma_vektorleri

array([[3., 2., 0., 0.],
       [2., 2., 3., 1.],
       [6., 4., 0., 0.]])

In [41]:
def cos_similarity(v1, v2):
    return np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))


cos_similarity(np.array([1, 2]), np.array([3, 4]))

0.9838699100999074

In [40]:
benzerlik_matrisi = np.zeros((len(dosya_yollari), len(dosya_yollari)))
benzerlik_matrisi

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
for i, doc_vektor_i in enumerate(sayma_vektorleri):
    for j, doc_vektor_j in enumerate(sayma_vektorleri):
        benzerlik = cos_similarity(doc_vektor_i, doc_vektor_j)
        if i == j:
            benzerlik_matrisi[i][j] = -2
        else:
            benzerlik_matrisi[i][j] = benzerlik

In [48]:
benzerlik_matrisi

array([[-2.        ,  0.65372045,  1.        ],
       [ 0.65372045, -2.        ,  0.65372045],
       [ 1.        ,  0.65372045, -2.        ]])

In [57]:
arr = np.array([1, 3.65, -2., 3.65])
np.argmax(arr)

1

In [54]:
def en_benzeri_hangisi(doc_index, dosya_yollari):
    """
    doc_index = 0 verilirse -> 0. doc'un (d1.txt) en benzeri hangisi?
    """
    satir = benzerlik_matrisi[doc_index]
    en_benzer_dosya_idx = np.argmax(satir)
    return dosya_yollari[en_benzer_dosya_idx]

In [58]:
en_benzeri_hangisi(2, dosya_yollari)

'/content/d1.txt'