In [2]:
import numpy as np

In [3]:
dosya_adlari = [
    "d1.txt",
    "d2.txt",
    "d3.txt",
    "d4.txt"
]

In [ ]:
w2i = {"<unk>": 0}
i = 1
for dosya_adi in dosya_adlari:
    with open(dosya_adi, "r") as in_file:
        lines = in_file.readlines()
        line = lines[0]
        tokens = line.split()
        for token in tokens:
            if token not in w2i:
                w2i[token] = i
                i += 1

print(w2i)

{'<unk>': 0, 'a': 1, 'b': 2, 'c': 3, 'd': 4}


In [ ]:
voc_size = len(w2i)
doc_mat = np.zeros((len(dosya_adlari), voc_size))

for i, dosya_adi in enumerate(dosya_adlari):

    with open(dosya_adi, "r") as in_file:
        lines = in_file.readlines()
        line = lines[0]
        tokens = line.split()
        for token in tokens:
            if token in w2i:
                token_index = w2i[token]
                doc_mat[i][token_index] += 1

print(doc_mat)

[[0. 6. 2. 0. 0.]
 [0. 3. 2. 2. 0.]
 [0. 3. 3. 2. 0.]
 [0. 0. 1. 2. 3.]]


In [ ]:
def dot_prod(v1, v2):
    """ 
    v1: [1, 3]; v2: [2, 7]
    v1 . v2 = 1*2 + 3*7 ->23
    """
    toplam = 0
    for v1_i, v2_i in zip(v1, v2):
        carpim = v1_i * v2_i
        toplam += carpim

    return toplam


dot_prod(np.array([1, 3]), np.array([2, 7]))

np.int64(23)

In [ ]:
def vec_norm(v):
    """ 
    v: [3, 4, 0] -> 5
    """
    toplam = 0
    for v_i in v:
        toplam += v_i ** 2

    return np.sqrt(toplam)


vec_norm(np.array([3, 4, 0]))

np.float64(5.0)

In [ ]:
def cos_sim(v1, v2):
    pay = dot_prod(v1, v2)
    payda = vec_norm(v1) * vec_norm(v2)
    return pay / payda


print(cos_sim(np.array([1, 2]), np.array([2, 4])))
print(cos_sim(np.array([1, 2]), np.array([-1, -2])))
print(cos_sim(np.array([0, 2]), np.array([2, 0])))

0.9999999999999998
-0.9999999999999998
0.0


In [ ]:
def doc2vec(doc, w2i):
    """
    doc2vec("a b b x y a", w2i) -> [2, 2, 2, 0, 0]
    """
    vec = np.zeros(len(w2i))
    tokens = doc.split()
    for token in tokens:
        if token in w2i:
            vec[w2i[token]] += 1
        else:
            vec[w2i["<unk>"]] += 1
    return vec


doc2vec("a b b x y a", w2i)

array([2., 2., 2., 0., 0.])

In [ ]:
query = "a b b x y a"
query_vec = doc2vec(query, w2i)

similarities = []

for doc_vec in doc_mat:
    sim = cos_sim(query_vec, doc_vec)
    similarities.append(sim)

similarities = np.array(similarities)
print(similarities)
print(np.argmax(similarities))
print(dosya_adlari[np.argmax(similarities)])

[0.73029674 0.70014004 0.73854895 0.15430335]
2
d3.txt
